print("Hello! Welcome to Rock Paper Scissors! \nRock \nPaper \nScissors!")
player_one = input("Enter Player One's Choice: ")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
print("No peaking")
player_two = input("Enter Player Two's Choice: ")
print("And the winner is:")
if player_one == "rock": 
	if player_two == "scissors":
		print("Player one!")
	if player_two == "paper":
		print("Player two!")
elif player_one == "scissors":
	if player_two == "paper":
		print("Player one!")
	if player_two == "rock":
		print("Player two!")
elif player_one == "paper": 
	if player_two == "rock":
		print("Player one!")
	if player_two == "scissors":
		print("Player two!")
else:
	print("It's a draw!")

